//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareemAdminMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Driver
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Please provide name", AllowEmptyStrings = false)]
        public string name { get; set; }

        [Required(ErrorMessage = "please provide License Number", AllowEmptyStrings = false)]
        public string licenseNo { get; set; }

        [Required(ErrorMessage = "Please provide Vichle Number", AllowEmptyStrings = false)]
        public string vichleNo { get; set; }

        [Required(ErrorMessage = "Please provide status", AllowEmptyStrings = false)]
        public string status { get; set; }

        [Required(ErrorMessage = "Please provide City", AllowEmptyStrings = false)]
        public string city { get; set; }
        [Required(ErrorMessage = "Please provide Email", AllowEmptyStrings = false)]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
            ErrorMessage = "Please provide valid email id")]
        public string email { get; set; }
    }
}
